?start : expr

?expr : atom | list | quote

?number : INT | FLOAT

?atom : (number | STRING | SYMBOL) -> atom

?list : "(" expr* ")" -> list

?quote: ("'"expr*) -> quote

// Terminais
SYMBOL.0  : /[-!+\/*@$%^#&~<>?|\\\w=]+/
STRING    : /"[^"\\]*(\\[^\n\t\r\f][^"\\]*)*"/
INT.1     : /-?\d+/
FLOAT.2   : /-?\d+\.\d+/
COMMENT    : "//" /[^\n]/*



%import common.WS_INLINE

%ignore /\s+/
%ignore /;[^\n]*/
%ignore WS_INLINE
%ignore COMMENT