?start : expr+

?expr: atom | list

?number : INT | FLOAT
	
?atom: (number | STRING | SYMBOL | LSQB) -> atom
	 
?list : "[" expr (","expr)* "]"

// Terminais
SYMBOL.0   : /[-!+\/*@$%^&~<>#?|\\\w=]+/
STRING     : /"[^"\\]*(\\[^\n\t\r\f][^"\\]*)*"/
INT.1      : /-?\d+/
FLOAT.2    : /-?\d+\.\d+/
LSQB       : /\[+/
//JSON     : "(\w|\\"|\\/|\\f|\\n|\\b| )*"
//COMMENT  : "//" /[^\n]/*
//ESCAPE   : "\\" ( "$" | "\"")

%ignore /\s+/
%ignore /;[^\n]*/

